
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int ELSE = 24;
  public static final int PLUS = 3;
  public static final int INT = 28;
  public static final int DIFFTHAN = 21;
  public static final int GREATEREQTHAN = 19;
  public static final int RBRACE = 12;
  public static final int RPAREN = 8;
  public static final int EQUAL = 20;
  public static final int WHILE = 25;
  public static final int SEMI = 2;
  public static final int IDENTIFIER = 29;
  public static final int RETURN = 26;
  public static final int IF = 23;
  public static final int LPAREN = 7;
  public static final int LBRACKET = 13;
  public static final int LBRACE = 11;
  public static final int RBRACKET = 14;
  public static final int LESSEQTHAN = 18;
  public static final int COMMA = 15;
  public static final int LESSTHAN = 16;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int DIVIDE = 9;
  public static final int SET = 22;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int VOID = 27;
  public static final int GREATERTHAN = 17;
  public static final int UMINUS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "DIVIDE",
  "NUMBER",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "LESSTHAN",
  "GREATERTHAN",
  "LESSEQTHAN",
  "GREATEREQTHAN",
  "EQUAL",
  "DIFFTHAN",
  "SET",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "VOID",
  "INT",
  "IDENTIFIER"
  };
}

